"""Japan Meteorological Agency tide data source.

JMA publishes a year's tide table for each of its stations as a text
file, one fixed-width line a day:

  columns   1-72   the hourly heights, 0h to 23h, three characters each
           73-78   the date as YYMMDD, two characters to a part
           79-80   the station's code
          81-108   up to four high waters, each HHMM and a height
         109-136   up to four low waters, the same

Heights are centimetres above the station's tide-table datum (潮位表
基準面), the mean low water of spring tides and close to chart datum;
this module converts to feet for the NOAA-shaped pipeline.  Times are
JST (UTC+9, no DST).  A slot with no tide in it reads 9999 for its time.
The tables run from 2011, and next year's is published in advance.

About seventy of the stations are JMA's own gauges, and what they
measured is published a month to a file in the same layout: the final
heights, highs and lows about three weeks after the month ends, and
before that the preliminary hourly heights alone.  Those are over the
gauge's own datum (観測基準面), not the table's.  The deviation files,
observed less predicted on the hour, tie the two: the prediction plus
the deviation less the observation comes out the same whole number of
centimetres at every hour of a year, and adding it puts what the gauge
measured on the table's datum.

The station list is JMA's list of tide-table stations, baked below by
scripts/build_jma_tide_stations.py.  The list is in Japanese only, and
the romanized names are on each station's own page, so both are kept: a
reader in Japanese sees the Japanese name, everyone else the romanized.
"""

from datetime import date, datetime, timedelta, timezone, tzinfo
from statistics import median
from typing import Any

from linecast._cache import location_cache_key
from linecast._http import HTTPError, fetch_bytes, fetch_json_cached
from linecast._log import log_skipped
from linecast.tides.common import (
    M_TO_FT, cache_dir, cached_y_range, local_day_bounds, month_after,
    nearest_station, station_coords, y_range_window,
)

JMA_BASE = "https://www.data.jma.go.jp"
# Japan does not observe DST; JST is always UTC+9.
JST = timezone(timedelta(hours=9))
# The first year JMA publishes a table for; earlier years are not there.
FIRST_YEAR = 2011
CM_TO_FT = M_TO_FT / 100
ID_PREFIX = "jma:"

# (code, Japanese name, romanized name, lat, lng), generated by
# scripts/build_jma_tide_stations.py from JMA's list of tide-table
# stations.  Every romanized name is JMA's own, from the heading of the
# station's table page, where it is in capitals; only the case is
# changed.  JMA writes a compound as one word (Tomakomaihigashi,
# Shimizuminato) and drops the long vowels' macrons.
_TABLE = (
    ("WN", "稚内", "Wakkanai", 45.4000, 141.6833),
    ("KE", "枝幸", "Esashi", 44.9333, 142.5833),
    ("A0", "紋別", "Monbetsu", 44.3500, 143.3667),
    ("AS", "網走", "Abashiri", 44.0167, 144.2833),
    ("A6", "羅臼", "Rausu", 44.0167, 145.2000),
    ("NM", "根室", "Nemuro", 43.3500, 145.5833),
    ("HN", "花咲", "Hanasaki", 43.2833, 145.5667),
    ("KP", "霧多布", "Kiritappu", 43.0833, 145.1167),
    ("KR", "釧路", "Kushiro", 42.9833, 144.3667),
    ("B1", "十勝", "Tokachi", 42.3000, 143.3167),
    ("A9", "浦河", "Urakawa", 42.1667, 142.7667),
    ("C8", "苫小牧東", "Tomakomaihigashi", 42.6000, 141.8167),
    ("TM", "苫小牧西", "Tomakomainishi", 42.6333, 141.6167),
    ("SO", "白老", "Shiraoi", 42.5167, 141.3167),
    ("A8", "室蘭", "Muroran", 42.3500, 140.9500),
    ("A3", "森", "Mori", 42.1167, 140.6000),
    ("HK", "函館", "Hakodate", 41.7833, 140.7167),
    ("Q0", "吉岡", "Yoshioka", 41.4500, 140.2333),
    ("A5", "松前", "Matsumae", 41.4167, 140.1000),
    ("ES", "江差", "Esashi", 41.8667, 140.1333),
    ("ZP", "奥尻", "Okushiri", 42.0833, 139.4833),
    ("OR", "奥尻港", "Okushiriko", 42.1667, 139.5167),
    ("SE", "瀬棚", "Setana", 42.4500, 139.8500),
    ("B6", "寿都", "Suttsu", 42.8000, 140.2333),
    ("B5", "岩内", "Iwanai", 42.9833, 140.5000),
    ("Z8", "忍路", "Oshoro", 43.2167, 140.8667),
    ("B3", "小樽", "Otaru", 43.2000, 141.0000),
    ("IK", "石狩新港", "Ishikarishinko", 43.2167, 141.3000),
    ("B2", "留萌", "Rumoi", 43.9500, 141.6333),
    ("F3", "沓形", "Kutsugata", 45.1833, 141.1333),
    ("Q1", "竜飛", "Tappi", 41.2500, 140.3833),
    ("AO", "青森", "Aomori", 40.8333, 140.7667),
    ("ZA", "浅虫", "Asamushi", 40.9000, 140.8667),
    ("Q2", "大湊", "Ominato", 41.2500, 141.1500),
    ("B4", "大間", "Oma", 41.5333, 140.9000),
    ("SH", "下北", "Shimokita", 41.3667, 141.2333),
    ("XS", "むつ小川原", "Mutsuogawara", 40.9333, 141.3833),
    ("HG", "八戸港", "Hachinoheko", 40.5333, 141.5500),
    ("XT", "久慈", "Kuji", 40.2000, 141.8000),
    ("MY", "宮古", "Miyako", 39.6500, 141.9833),
    ("Q6", "釜石", "Kamaishi", 39.2667, 141.8833),
    ("OF", "大船渡", "Ofunato", 39.0167, 141.7500),
    ("AY", "鮎川", "Ayukawa", 38.3000, 141.5000),
    ("E6", "石巻", "Ishinomaki", 38.4000, 141.2667),
    ("SG", "塩釜", "Shiogama", 38.3167, 141.0333),
    ("SD", "仙台新港", "Sendaishinko", 38.2667, 141.0000),
    ("ZM", "相馬", "Soma", 37.8333, 140.9667),
    ("ON", "小名浜", "Onahama", 36.9333, 140.9000),
    ("D1", "日立", "Hitachi", 36.5000, 140.6333),
    ("D3", "大洗", "Oarai", 36.3000, 140.5667),
    ("D2", "鹿島", "Kashima", 35.9333, 140.7000),
    ("CS", "銚子漁港", "Choshigyoko", 35.7500, 140.8667),
    ("ZF", "勝浦", "Katsuura", 35.1333, 140.2500),
    ("MR", "布良", "Mera", 34.9167, 139.8333),
    ("TT", "館山", "Tateyama", 34.9833, 139.8500),
    ("KZ", "木更津", "Kisarazu", 35.3667, 139.9167),
    ("QL", "千葉", "Chiba", 35.5667, 140.0500),
    ("CB", "千葉港", "Chibako", 35.6000, 140.1000),
    ("TK", "東京", "Tokyo", 35.6500, 139.7667),
    ("KW", "川崎", "Kawasaki", 35.5167, 139.7500),
    ("YK", "京浜港", "Keihinko", 35.4667, 139.6333),
    ("QS", "横浜", "Yokohama", 35.4500, 139.6500),
    ("HM", "本牧", "Honmoku", 35.4333, 139.6667),
    ("QN", "横須賀", "Yokosuka", 35.2833, 139.6500),
    ("Z1", "油壺", "Aburatsubo", 35.1667, 139.6167),
    ("OK", "岡田", "Okada", 34.7833, 139.3833),
    ("QO", "神津島", "Kozushima", 34.2167, 139.1333),
    ("MJ", "三宅島（坪田）", "Miyakejima (Tsubota)", 34.0500, 139.5500),
    ("QP", "三宅島（阿古）", "Miyakejima (Ako)", 34.0667, 139.4833),
    ("D4", "八丈島（八重根）", "Hachijojima (Yaene)", 33.1000, 139.7667),
    ("QQ", "八丈島（神湊）", "Hachijojima (Kaminato)", 33.1333, 139.8000),
    ("CC", "父島", "Chichijima", 27.1000, 142.2000),
    ("MC", "南鳥島", "Minamitorishima", 24.2833, 153.9833),
    ("D8", "湘南港", "Shonanko", 35.3000, 139.4833),
    ("OD", "小田原", "Odawara", 35.2333, 139.1500),
    ("Z3", "伊東", "Ito", 34.9000, 139.1333),
    ("D6", "下田", "Shimoda", 34.6833, 138.9667),
    ("QK", "南伊豆", "Minamiizu", 34.6333, 138.8833),
    ("G9", "石廊崎", "Irozaki", 34.6167, 138.8500),
    ("Z4", "田子", "Tago", 34.8000, 138.7667),
    ("UC", "内浦", "Uchiura", 35.0167, 138.8833),
    ("SM", "清水港", "Shimizuminato", 35.0167, 138.5167),
    ("Z5", "焼津", "Yaizu", 34.8667, 138.3333),
    ("OM", "御前崎", "Omaezaki", 34.6167, 138.2167),
    ("MI", "舞阪", "Maisaka", 34.6833, 137.6167),
    ("I4", "赤羽根", "Akabane", 34.6000, 137.1833),
    ("G4", "三河", "Mikawa", 34.7333, 137.3167),
    ("G5", "形原", "Katahara", 34.7833, 137.1833),
    ("G8", "衣浦", "Kinuura", 34.8833, 136.9500),
    ("ZD", "鬼崎", "Onizaki", 34.9000, 136.8167),
    ("NG", "名古屋", "Nagoya", 35.0833, 136.8833),
    ("G3", "四日市港", "Yokkaichiko", 34.9667, 136.6333),
    ("TB", "鳥羽", "Toba", 34.4833, 136.8167),
    ("OW", "尾鷲", "Owase", 34.0833, 136.2000),
    ("KN", "熊野", "Kumano", 33.9333, 136.1667),
    ("UR", "浦神", "Uragami", 33.5667, 135.9000),
    ("KS", "串本", "Kushimoto", 33.4833, 135.7667),
    ("SR", "白浜", "Shirahama", 33.6833, 135.3833),
    ("GB", "御坊", "Gobo", 33.8500, 135.1667),
    ("H1", "下津", "Shimotsu", 34.1167, 135.1333),
    ("Z9", "海南", "Kainan", 34.1500, 135.2000),
    ("WY", "和歌山", "Wakayama", 34.2167, 135.1500),
    ("TN", "淡輪", "Tannowa", 34.3333, 135.1833),
    ("KK", "関空島", "Kankujima", 34.4333, 135.2000),
    ("J2", "岸和田", "Kishiwada", 34.4667, 135.3667),
    ("IO", "泉大津", "Izumiotsu", 34.5167, 135.4000),
    ("SI", "堺", "Sakai", 34.6000, 135.4667),
    ("OS", "大阪", "Osaka", 34.6500, 135.4333),
    ("AM", "尼崎", "Amagasaki", 34.7000, 135.4000),
    ("J5", "西宮", "Nishinomiya", 34.7167, 135.3333),
    ("KB", "神戸", "Kobe", 34.6833, 135.1833),
    ("AK", "明石", "Akashi", 34.6500, 134.9833),
    ("ST", "洲本", "Sumoto", 34.3500, 134.9000),
    ("EI", "江井", "Ei", 34.4667, 134.8333),
    ("K1", "姫路（飾磨）", "Himeji", 34.7833, 134.6667),
    ("SB", "三蟠", "Sanban", 34.6000, 133.9833),
    ("UN", "宇野", "Uno", 34.4833, 133.9500),
    ("MM", "水島", "Mizushima", 34.5333, 133.7333),
    ("LG", "乙島", "Otoshima", 34.5000, 133.6833),
    ("IZ", "糸崎", "Itozaki", 34.4000, 133.0833),
    ("TH", "竹原", "Takehara", 34.3333, 132.9167),
    ("Q9", "呉", "Kure", 34.2333, 132.5500),
    ("Q8", "広島", "Hiroshima", 34.3500, 132.4667),
    ("QA", "徳山", "Tokuyama", 34.0333, 131.8000),
    ("J9", "三田尻", "Mitajiri", 34.0333, 131.5833),
    ("WH", "宇部", "Ube", 33.9333, 131.2500),
    ("CF", "長府", "Chofu", 34.0167, 131.0000),
    ("A1", "弟子待", "Deshimatsu", 33.9333, 130.9333),
    ("TI", "田ノ首", "Tanokubi", 33.9167, 130.9167),
    ("OH", "大山の鼻", "Oyamanohana", 33.9167, 130.9000),
    ("HR", "南風泊", "Haedomari", 33.9500, 130.8833),
    ("MT", "松山", "Matsuyama", 33.8667, 132.7167),
    ("M3", "波止浜", "Hashihama", 34.1000, 132.9333),
    ("M0", "今治市小島", "Imabarishioshima", 34.1333, 132.9833),
    ("M1", "来島航路", "Kurushimakoro", 34.1167, 132.9833),
    ("L0", "今治", "Imabari", 34.0667, 133.0000),
    ("NI", "新居浜", "Niihama", 33.9667, 133.2667),
    ("L8", "伊予三島", "Iyomishima", 33.9833, 133.5500),
    ("TX", "多度津", "Tadotsu", 34.2833, 133.7500),
    ("AX", "青木", "Aoki", 34.3667, 133.6833),
    ("J8", "与島", "Yoshima", 34.3833, 133.8167),
    ("TA", "高松", "Takamatsu", 34.3500, 134.0500),
    ("KM", "小松島", "Komatsushima", 34.0167, 134.5833),
    ("J6", "橘", "Tachibana", 33.8667, 134.6333),
    ("AW", "阿波由岐", "Awayuki", 33.7667, 134.6000),
    ("HW", "日和佐", "Hiwasa", 33.7167, 134.5500),
    ("L7", "甲浦", "Kannoura", 33.5500, 134.3000),
    ("MU", "室戸岬", "Murotomisaki", 33.2667, 134.1667),
    ("KC", "高知", "Kochi", 33.5000, 133.5667),
    ("V7", "須崎", "Susaki", 33.3833, 133.3000),
    ("ZH", "久礼", "Kure", 33.3333, 133.2500),
    ("L6", "高知下田", "Kochishimoda", 32.9333, 133.0000),
    ("TS", "土佐清水", "Tosashimizu", 32.7833, 132.9667),
    ("SU", "片島", "Katashima", 32.9167, 132.7000),
    ("UW", "宇和島", "Uwajima", 33.2333, 132.5500),
    ("N1", "日明", "Hiagari", 33.9167, 130.8833),
    ("N0", "砂津", "Sunatsu", 33.9000, 130.8833),
    ("MO", "門司", "Moji", 33.9500, 130.9500),
    ("AH", "青浜", "Aohama", 33.9500, 131.0167),
    ("O3", "苅田", "Kanda", 33.8000, 131.0000),
    ("BP", "別府", "Beppu", 33.3000, 131.5000),
    ("QC", "大分", "Oita", 33.2667, 131.6833),
    ("X5", "佐伯", "Saiki", 32.9500, 131.9667),
    ("Z6", "細島", "Hosojima", 32.4333, 131.6667),
    ("MG", "宮崎", "Miyazaki", 31.9000, 131.4500),
    ("AB", "油津", "Aburatsu", 31.5833, 131.4167),
    ("X6", "志布志", "Shibushi", 31.4833, 131.1167),
    ("QG", "大泊", "Odomari", 31.0167, 130.6833),
    ("KG", "鹿児島", "Kagoshima", 31.6000, 130.5667),
    ("MK", "枕崎", "Makurazaki", 31.2667, 130.3000),
    ("ZJ", "阿久根", "Akune", 32.0167, 130.1833),
    ("QH", "西之表", "Nishinoomote", 30.7333, 131.0000),
    ("TJ", "種子島", "Tanegashima", 30.4667, 130.9667),
    ("QI", "中之島", "Nakanoshima", 29.8500, 129.8500),
    ("QJ", "名瀬", "Naze", 28.4000, 129.5000),
    ("O9", "奄美", "Amami", 28.3167, 129.5333),
    ("NK", "中城湾港", "Nakagusukuwanko", 26.3333, 127.8333),
    ("ZO", "沖縄", "Okinawa", 26.1833, 127.8167),
    ("NH", "那覇", "Naha", 26.2167, 127.6667),
    ("DJ", "南大東", "Minamidaito", 25.8667, 131.2333),
    ("R1", "平良", "Hirara", 24.8167, 125.2833),
    ("IS", "石垣", "Ishigaki", 24.3333, 124.1667),
    ("IJ", "西表", "Iriomote", 24.3500, 123.7500),
    ("YJ", "与那国", "Yonaguni", 24.4500, 122.9500),
    ("O7", "水俣", "Minamata", 32.2000, 130.3667),
    ("O5", "八代", "Yatsushiro", 32.5167, 130.5667),
    ("HS", "本渡瀬戸", "Hondoseto", 32.4333, 130.2167),
    ("RH", "苓北", "Reihoku", 32.4667, 130.0333),
    ("MS", "三角", "Misumi", 32.6167, 130.4500),
    ("KU", "熊本", "Kumamoto", 32.7500, 130.5667),
    ("O6", "大牟田", "Omuta", 33.0167, 130.4167),
    ("OU", "大浦", "Oura", 32.9833, 130.2167),
    ("KT", "口之津", "Kuchinotsu", 32.6000, 130.2000),
    ("NS", "長崎", "Nagasaki", 32.7333, 129.8667),
    ("KO", "皇后", "Kogo", 32.7167, 129.8333),
    ("FE", "福江", "Fukue", 32.7000, 128.8500),
    ("QD", "佐世保", "Sasebo", 33.1500, 129.7167),
    ("X2", "平戸瀬戸", "Hiradoseto", 33.3667, 129.5833),
    ("ZL", "仮屋", "Kariya", 33.4667, 129.8500),
    ("KA", "唐津", "Karatsu", 33.4667, 129.9667),
    ("QF", "博多", "Hakata", 33.6167, 130.4000),
    ("X3", "郷ノ浦", "Gonoura", 33.7500, 129.6833),
    ("QE", "厳原", "Izuhara", 34.2000, 129.3000),
    ("O1", "対馬", "Tsushima", 34.2667, 129.3167),
    ("N5", "対馬比田勝", "Tsushimahitakatsu", 34.6500, 129.4833),
    ("K5", "萩", "Hagi", 34.4333, 131.4167),
    ("ZK", "須佐", "Susa", 34.6333, 131.6000),
    ("HA", "浜田", "Hamada", 34.9000, 132.0667),
    ("SK", "境", "Sakai", 35.5500, 133.2500),
    ("SA", "西郷", "Saigo", 36.2000, 133.3333),
    ("ZE", "田後", "Tajiri", 35.6000, 134.3167),
    ("T6", "津居山", "Tsuiyama", 35.6500, 134.8333),
    ("T2", "宮津", "Miyazu", 35.5333, 135.2000),
    ("MZ", "舞鶴", "Maizuru", 35.4833, 135.3833),
    ("XM", "敦賀", "Tsuruga", 35.6667, 136.0667),
    ("ZG", "三国", "Mikuni", 36.2500, 136.1500),
    ("T1", "金沢", "Kanazawa", 36.6167, 136.6000),
    ("Z7", "輪島", "Wajima", 37.4000, 136.9000),
    ("SZ", "能登", "Noto", 37.5000, 137.1500),
    ("XO", "七尾", "Nanao", 37.0500, 136.9667),
    ("XQ", "伏木富山", "Fushikitoyama", 36.8000, 137.0667),
    ("SN", "新湊", "Shinminato", 36.7833, 137.1167),
    ("TY", "富山", "Toyama", 36.7667, 137.2167),
    ("I7", "生地", "Ikuji", 36.8833, 137.4167),
    ("T3", "直江津", "Naoetsu", 37.1833, 138.2500),
    ("ZC", "柏崎", "Kashiwazaki", 37.3500, 138.5167),
    ("S6", "新潟西港", "Niigatanishiko", 37.9333, 139.0667),
    ("I5", "新潟東港", "Niigatahigashiko", 37.9833, 139.2167),
    ("ZN", "小木", "Ogi", 37.8167, 138.2833),
    ("RZ", "両津", "Ryotsu", 38.0833, 138.4333),
    ("S0", "佐渡", "Sado", 38.3167, 138.5167),
    ("QR", "粟島", "Awashima", 38.4667, 139.2500),
    ("ZB", "鼠ヶ関", "Nezugaseki", 38.5667, 139.5500),
    ("S9", "酒田", "Sakata", 38.9167, 139.8167),
    ("ZQ", "飛島", "Tobishima", 39.1833, 139.5500),
    ("S1", "秋田", "Akita", 39.7500, 140.0667),
    ("S2", "船川港", "Funakawako", 39.9167, 139.8500),
    ("ZI", "男鹿", "Oga", 39.9500, 139.7000),
    ("FK", "深浦", "Fukaura", 40.6500, 139.9333),
)
STATIONS = [dict(zip(("id", "name_ja", "name", "lat", "lng"), row)) for row in _TABLE]
STATION_BY_CODE = {s["id"]: s for s in STATIONS}

# The stations whose gauge JMA runs and publishes the measurements of,
# from its list of observing stations.
GAUGES = frozenset((
    "AB", "AS", "AW", "AY", "B3", "CC", "DJ", "FE", "FK", "G9", "GB", "HA",
    "HK", "HN", "I4", "IS", "KB", "KC", "KG", "KM", "KN", "KR", "KS", "KT",
    "MC", "MI", "MJ", "MK", "MR", "MT", "MU", "MY", "MZ", "N5", "NG", "NH",
    "NS", "O9", "OD", "OF", "OK", "OM", "ON", "OS", "OU", "OW", "RH", "S0",
    "SA", "SH", "SK", "SM", "SR", "ST", "SZ", "TA", "TB", "TJ", "TK", "TN",
    "TS", "TY", "UC", "UN", "UR", "UW", "WN", "WY", "X5", "YJ",
))


# ---------------------------------------------------------------------------
# Station IDs and names
# ---------------------------------------------------------------------------
def station_code(station_id: str) -> str | None:
    """The two-character JMA code in a "jma:TK" ID, or None."""
    if station_id[:len(ID_PREFIX)].lower() != ID_PREFIX:
        return None
    code = station_id[len(ID_PREFIX):].upper()
    return code if code in STATION_BY_CODE else None


def is_jma_station_id(text: str) -> bool:
    """True for "jma:" and one of the codes above, in any case."""
    return station_code(text) is not None


def _station_id(code: str) -> str:
    return f"{ID_PREFIX}{code}"


def display_name(station: dict[str, Any]) -> str:
    """The station's name in Japanese for a reader in Japanese, else
    romanized.  The provider interface has no runtime to ask, so the
    running command's is read."""
    from linecast._i18n import lang_of
    from linecast._runtime import current_runtime
    if lang_of(current_runtime()) == "ja":
        return station["name_ja"]
    return station["name"]


def find_nearest_station_jma(lat: float, lng: float) -> tuple[str | None, str | None]:
    """The closest station within 100 nm as (id, name), else (None, None).
    The name is looked up afresh, as the reader's language may have
    changed since the pick was cached."""
    station_id, _name = nearest_station(
        cache_dir() / f"jma_station_{location_cache_key(lat, lng)}.json",
        lat, lng, lambda: STATIONS, station_coords,
        lambda s: (_station_id(s["id"]), s["name"]), tag="tides/jma",
    )
    code = station_code(station_id) if station_id else None
    if code is None:
        return None, None
    return station_id, display_name(STATION_BY_CODE[code])


def fetch_station_metadata_jma(station_id: str) -> dict[str, Any] | None:
    """Station metadata in the shape the NOAA pipeline reads."""
    code = station_code(station_id)
    if code is None:
        return None
    s = STATION_BY_CODE[code]
    return {
        "id": _station_id(code),
        "name": display_name(s),
        "state": "JP",
        "lat": s["lat"],
        "lng": s["lng"],
        "timezone_abbr": "JST",
        "timezonecorr": 9,
        "timeZoneCode": "Asia/Tokyo",
        "observedst": False,
        "source": "jma",
    }


# ---------------------------------------------------------------------------
# Files
# ---------------------------------------------------------------------------
def _fetch_text(url: str, timeout: float) -> str:
    """The file at *url*, or "" when there is none: a year or month not
    published yet is an answer, kept like any other, so it is not asked
    for again until the cached copy ages out."""
    try:
        return fetch_bytes(url, timeout=timeout).decode("ascii", "replace")
    except HTTPError as exc:
        if exc.code == 404:
            return ""
        raise


def _lines(text: str) -> list[str]:
    # Every file's lines carry the date and code by column 80, which a
    # line cut short in transit would not.
    return [line for line in text.splitlines() if len(line) >= 80]


def _fetch_lines(cache_file, max_age: float, url: str) -> list[str]:
    data = fetch_json_cached(cache_file, max_age, url, timeout=20, fallback=None,
                             fetch=_fetch_text, transform=_lines, provider="tides/jma")
    return data if isinstance(data, list) else []


def _fetch_year(code: str, year: int) -> list[str]:
    """The lines of one year's tide table, or [] when unavailable.

    A past year's predictions never change, so those are kept for 30
    days; the current and coming years for a day, in case JMA revises
    them.
    """
    if year < FIRST_YEAR:
        return []
    max_age = 30 * 86400 if year < datetime.now(JST).year else 86400
    return _fetch_lines(cache_dir() / f"jma_pred_{code}_{year}.json", max_age,
                        f"{JMA_BASE}/kaiyou/data/db/tide/suisan/txt/{year}/{code}.txt")


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------
def _day(line: str) -> date | None:
    try:
        return date(2000 + int(line[72:74]), int(line[74:76]), int(line[76:78]))
    except ValueError:
        return None


def _hourly(line: str) -> list[int | None]:
    """The line's 24 hourly heights in cm; None for an hour the gauge
    missed, which the observed files leave blank."""
    heights = []
    for hour in range(24):
        field = line[hour * 3:hour * 3 + 3].strip()
        try:
            heights.append(int(field))
        except ValueError:
            heights.append(None)
    return heights


def _turns(line: str, day: date, start: int) -> list[tuple[datetime, int]]:
    """Up to four (datetime_jst, cm) turning points from the seven-column
    slots at *start*.  An unused slot reads 9999 for its time, and one
    the gauge missed is blank."""
    out = []
    for slot in range(4):
        field = line[start + slot * 7:start + slot * 7 + 7]
        hhmm = field[:4]
        if not hhmm.strip() or hhmm == "9999":
            continue
        try:
            dt = datetime(day.year, day.month, day.day,
                          int(hhmm[:2]), int(hhmm[2:]), tzinfo=JST)
            out.append((dt, int(field[4:])))
        except ValueError:
            continue
    return out


def parse_hourly(lines: list[str]) -> list[tuple[datetime, float]]:
    """(datetime_jst, height_ft) points from a table's lines."""
    points = []
    dropped = 0
    for line in lines:
        day = _day(line)
        if day is None:
            dropped += 1
            continue
        midnight = datetime(day.year, day.month, day.day, tzinfo=JST)
        for hour, cm in enumerate(_hourly(line)):
            if cm is not None:
                points.append((midnight + timedelta(hours=hour), cm * CM_TO_FT))
    log_skipped("tides/jma", "hourly lines", dropped, len(lines))
    return points


def parse_hilo(lines: list[str]) -> list[tuple[datetime, float, str]]:
    """(datetime_jst, height_ft, "H"/"L") from a table's lines, in time
    order.  JMA lists the highs and lows apart, so nothing is inferred."""
    events = []
    dropped = 0
    for line in lines:
        day = _day(line)
        if day is None:
            dropped += 1
            continue
        for kind, start in (("H", 80), ("L", 108)):
            events.extend((dt, cm * CM_TO_FT, kind) for dt, cm in _turns(line, day, start))
    log_skipped("tides/jma", "high/low lines", dropped, len(lines))
    events.sort(key=lambda e: e[0])
    return events


# ---------------------------------------------------------------------------
# Ranges
# ---------------------------------------------------------------------------
def _years(station_id: str, start_date: date, end_date: date):
    """The table's lines for each year the range touches."""
    code = station_code(station_id)
    if code is None:
        return
    for year in range(start_date.year, end_date.year + 1):
        yield _fetch_year(code, year)


def fetch_tides_range_jma(station_id: str, start_date: date, end_date: date,
                          station_tz: tzinfo | None = None,
                          ) -> list[tuple[datetime, float]]:
    """Hourly predictions from *start_date* through *end_date*, as sorted
    (datetime, height_ft) points.  JMA is always JST, so *station_tz* is
    accepted for the provider interface and not needed."""
    lo, hi = local_day_bounds(start_date, end_date, JST)
    points = []
    for lines in _years(station_id, start_date, end_date):
        points.extend(p for p in parse_hourly(lines) if lo <= p[0] < hi)
    points.sort(key=lambda p: p[0])
    return points


def fetch_hilo_range_jma(station_id: str, start_date: date, end_date: date,
                         station_tz: tzinfo | None = None,
                         ) -> list[tuple[datetime, float, str]]:
    """Highs and lows from *start_date* through *end_date*, as sorted
    (datetime, height_ft, "H"/"L") tuples."""
    lo, hi = local_day_bounds(start_date, end_date, JST)
    events = []
    for lines in _years(station_id, start_date, end_date):
        events.extend(e for e in parse_hilo(lines) if lo <= e[0] < hi)
    events.sort(key=lambda e: e[0])
    return events


def fetch_y_range_jma(station_id: str, center_date: date,
                      station_tz: tzinfo | None = None) -> tuple[float, float] | None:
    """The y-axis range from the highs and lows around *center_date*.
    Cached 7 days, keyed by month like the other providers."""
    code = station_code(station_id)
    if code is None:
        return None
    start, end, key = y_range_window(center_date)

    def heights():
        hilo = fetch_hilo_range_jma(station_id, start, end, station_tz)
        if hilo:
            return [h for _, h, _ in hilo]
        return [h for _, h in fetch_tides_range_jma(station_id, start, end, station_tz)]

    return cached_y_range(cache_dir() / f"jma_yrange_{code}_{key}.json", heights)


# ---------------------------------------------------------------------------
# What the gauge measured
# ---------------------------------------------------------------------------
def _observed_url(kind: str, code: str, year: int, month: int, final: bool) -> str:
    """A month's file of *kind* ("hry" heights, "dep" deviations): the
    final one, or the preliminary one before it is out."""
    ym = f"{year}{month:02d}"
    if final:
        return f"{JMA_BASE}/kaiyou/data/db/tide/genbo/{year}/{ym}/{kind}{ym}{code}.txt"
    return f"{JMA_BASE}/kaiyou/data/db/tide/sokuho/{ym}/z_{kind}{ym}{code}.txt"


def _observed_month(code: str, year: int, month: int,
                    today: date) -> tuple[list[str], bool]:
    """(lines, final) of what the gauge measured in a month.

    The final file comes out around the 20th of the month after; until
    then, and always for the month still running, the preliminary file
    stands in, kept three hours.  A final file is kept for a month once
    the month after has ended, and for a day before that, so one not out
    yet is asked for again tomorrow.
    """
    first = date(year, month, 1)
    if (year, month) != (today.year, today.month):
        settled = today >= month_after(month_after(first))
        lines = _fetch_lines(cache_dir() / f"jma_obs_{code}_{first:%Y%m}.json",
                             30 * 86400 if settled else 86400,
                             _observed_url("hry", code, year, month, final=True))
        # A settled month with no file is a gauge that was down; there
        # is no preliminary file that old to look for either.
        if lines or settled:
            return lines, True
    return _fetch_lines(cache_dir() / f"jma_obsz_{code}_{first:%Y%m}.json", 3 * 3600,
                        _observed_url("hry", code, year, month, final=False)), False


def _datum_offset(code: str, year: int, month: int, final: bool,
                  observed: list[str], predicted: list[str]) -> int | None:
    """The centimetres that put the gauge's heights on the tide table's
    datum, from a month of *observed* lines, the year's *predicted*
    ones, and the month's deviations; None when there are none to
    compare.  JMA figures the deviations from the table itself, so every
    hour gives the same number, and the median keeps a stray hour from
    mattering."""
    kept = 30 * 86400 if final else 3 * 3600
    tag = "dep" if final else "depz"
    deviations = _fetch_lines(cache_dir() / f"jma_{tag}_{code}_{year}{month:02d}.json", kept,
                              _observed_url("dep", code, year, month, final))
    predicted = {_day(line): _hourly(line) for line in predicted}
    measured = {_day(line): _hourly(line) for line in observed}
    offsets = []
    for line in deviations:
        # The deviation files write the date in full, after four columns
        # to each of the 24 hours.
        try:
            day = date(int(line[96:100]), int(line[100:102]), int(line[102:104]))
        except ValueError:
            continue
        pred, obs = predicted.get(day), measured.get(day)
        if pred is None or obs is None:
            continue
        for hour in range(24):
            try:
                dev = int(line[hour * 4:hour * 4 + 4])
            except ValueError:
                continue
            if pred[hour] is not None and obs[hour] is not None:
                offsets.append(pred[hour] + dev - obs[hour])
    return round(median(offsets)) if offsets else None


def _hourly_ranges(lines: list[str]) -> dict[date, tuple[int, int]]:
    """{day: (lowest, highest)} in cm from hourly heights alone, as the
    preliminary files give: the samples, and the high and low waters
    between them, found with a parabola through each turn and its
    neighbours, as for Open-Meteo's hourly series."""
    from linecast.tides.openmeteo import _extrema
    series = []
    for line in lines:
        day, hourly = _day(line), _hourly(line)
        # A day the file has not filled in yet, or with an hour the gauge
        # missed, would show a range narrower than the water's.
        if day is None or None in hourly:
            continue
        midnight = datetime(day.year, day.month, day.day, tzinfo=JST)
        series.extend((midnight + timedelta(hours=hour), cm)
                      for hour, cm in enumerate(hourly))
    series.sort(key=lambda p: p[0])
    # A parabola fits only three hours in a row, so the series is cut
    # where a day was left out.
    runs, run = [], []
    for point in series:
        if run and point[0] - run[-1][0] != timedelta(hours=1):
            runs.append(run)
            run = []
        run.append(point)
    runs.append(run)
    days = {}
    for run in runs:
        for dt, cm, *_kind in run + _extrema(run):
            lo, hi = days.get(dt.date(), (cm, cm))
            days[dt.date()] = (min(lo, cm), max(hi, cm))
    return days


def _final_ranges(lines: list[str]) -> dict[date, tuple[int, int]]:
    """{day: (lowest, highest)} in cm of the highs and lows a final file
    lists; a day whose turns the gauge missed falls to its hours."""
    days = {}
    for line in lines:
        day = _day(line)
        if day is None:
            continue
        turns = [cm for start in (80, 108) for _dt, cm in _turns(line, day, start)]
        if turns:
            days[day] = (min(turns), max(turns))
    missed = [line for line in lines if _day(line) not in days]
    if missed:
        days.update(_hourly_ranges(missed))
    return days


def fetch_observed_extremes_jma(station_id: str, year: int,
                                today: date) -> dict[date, tuple[float, float]]:
    """{day: (lowest, highest)} of the water the gauge measured in *year*
    before *today*, in feet above the tide table's datum; empty for a
    station JMA does not measure at.

    A month to a request, and one more for the deviations that give the
    datum: thirteen requests for a past year, kept for a month, and as
    many as the months so far for this one.
    """
    code = station_code(station_id)
    first = date(year, 1, 1)
    last = min(date(year, 12, 31), today - timedelta(days=1))
    if code not in GAUGES or last < first:
        return {}
    # The year's table is what ties the gauge's datum to the table's;
    # without it there is nothing to measure against.
    predicted = _fetch_year(code, year)
    if not predicted:
        return {}
    months = []
    for month in range(1, last.month + 1):
        lines, final = _observed_month(code, year, month, today)
        # A gauge that was down still has its file, every column blank
        if any(cm is not None for line in lines for cm in _hourly(line)):
            months.append((month, final, lines))
    offset = None
    for month, final, lines in months:
        offset = _datum_offset(code, year, month, final, lines, predicted)
        if offset is not None:
            break
    if offset is None:
        # Without the deviations there is no saying where the gauge's
        # datum sits, and a pen drawn on the wrong one misleads.
        return {}
    days = {}
    for _month, final, lines in months:
        ranges = _final_ranges(lines) if final else _hourly_ranges(lines)
        for day, (lo, hi) in ranges.items():
            if first <= day <= last:
                days[day] = ((lo + offset) * CM_TO_FT, (hi + offset) * CM_TO_FT)
    return days
